// Design a program that generates a random number between 1 and 100. The user is asked to guess
// the number. Use a do-while loop to continue prompting until the correct number is guessed.

// #include <stdio.h>
// #include <stdlib.h>
// #include <time.h>

#include<stdio.h>
#include <stdlib.h>
#include <time.h>   

int main()
{
    int guess, rendom;
    
    srand(time(0));
    rendom = rand() % 100 + 1; 

    do
    {
        printf("\nGuess the random number generated by the program: ");
        scanf("%d", &guess);

        if (guess > rendom)
        {
            printf("too high. try again");
        }
        else if (guess < rendom)
        {
            printf("too low. try again");
        }

    } while (guess != rendom);

    printf("\ncongratulations you guessed correct number %d", rendom);
    
}